# Generated by Django 6.0.2 on 2026-02-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
