# Generated by Django 6.0.2 on 2026-02-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='slug',
            new_name='blog_slug',
        ),
    ]
